# -------------------------------
# General
# -------------------------------
replicaCount: 1

# -------------------------------
# Image
# -------------------------------
image:
  repository: ghani9898/flask-app
  tag: 8da0ae0
  pullPolicy: IfNotPresent

# -------------------------------
# Service Account
# -------------------------------
serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}

# -------------------------------
# Resources
# -------------------------------
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi

# -------------------------------
# Probes
# -------------------------------
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

# -------------------------------
# Pod metadata
# -------------------------------
podAnnotations: {}
podLabels: {}

# -------------------------------
# Volumes
# -------------------------------
volumes: []
volumeMounts: []

# -------------------------------
# Scheduling
# -------------------------------
nodeSelector: {}
affinity: {}
tolerations: []

# -------------------------------
# Image Pull Secrets
# -------------------------------
imagePullSecrets: []

# -------------------------------
# Pod Security Context
# -------------------------------
podSecurityContext: {}

# -------------------------------
# Service
# -------------------------------
service:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    

# -------------------------------
# Ingress
# -------------------------------
ingress:
  enabled: false

# -------------------------------
# HTTPRoute (Gateway API)
# -------------------------------
httpRoute:
  enabled: false

# -------------------------------
# Autoscaling
# -------------------------------
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
