apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flask-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 5000       # service port
      targetPort: 5000 # container port
