name: CI-CD Flask App (Helm + ArgoCD)

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # 2️⃣ Login to Docker Hub (for base image & pushing final image)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build --no-cache -t ghani9898/flask-app:$IMAGE_TAG ./flask-app-code
          docker push ghani9898/flask-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4️⃣ Update Helm values.yaml
      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" values.yaml

      # 5️⃣ Commit and Push updated values.yaml
      - name: Commit and Push updated values.yaml
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "ci: update image tag to ${IMAGE_TAG}" || echo "No changes"
          git push
